name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: npm run esbuild-base -- --minify
      - name: Package extension
        run: npm run package
      - name: Create release
        uses: softprops/action-gh-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            *.vsix
      - name: Publish extension to VS Code Marketplace
        run: npx vsce publish -p $VSC_TOKEN
        env:
          VSC_TOKEN: ${{ secrets.VSC_TOKEN }}
      - name: Publish extension to Open VSX Registry
        run: npx ovsx publish -p $OVSX_TOKEN
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
